### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Madji** [uxbh/ztdns#11]
go get -u github.com/uxbh/ztdns/
# github.com/miekg/dns
Go/src/github.com/miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
Go/src/github.com/miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding

**Comment by AarynSmith** [comment]
This appears to be an upstream issue. 
https://github.com/miekg/dns/issues/687

Miekg suggests updating to go 1.9 or 1.10. What version are you running?

**Comment by Madji** [comment]
Thank you. Indeed, the version of go was 1.8.3. Updated version to go version go1.9.6 linux / amd64. Everything is working. downloaded, compiled. Thank you , great projects.
