### ISSUE TITLE
Unable to bind to port 53 for udp6

### ISSUE THREAD

**Issue by afeezaziz** [uxbh/ztdns#3]
Hi,

I keep getting: 
`FATA[0002] failed to start DNS server: listen udp6 [ee20::5cde:21ff:fe18:ca2c]:53: bind: invalid argument`

whenever I try to start the DNS server.

**Comment by AarynSmith** [comment]
Please see step 2 of the installing section of the README.md

> If you are running on linux, run sudo setcap cap_net_bind_service=+eip ./ztdns to enable non-root users to bind privalaged ports.
